apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-ingress-devops
  namespace: haproxy-controller-devops
  labels:
    app: haproxy-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy-ingress
  template:
    metadata:
      labels:
        app: haproxy-ingress
    spec:
      serviceAccountName: build-robot
      containers:
      - name: ingress-container-devops
        image: haproxytech/kubernetes-ingress
        args:
          - --default-backend-service=haproxy-controller-devops/service-backend-devops
        resources:
          requests:
            memory: "50Mi"
            cpu: "0.5"
        livenessProbe:
          httpGet:
            path: /text.html
            port: 1024
          initialDelaySeconds: 5
          periodSeconds: 5


