apiVersion: v1
kind: Service
metadata:
  name: service-backend-devops
  namespace: haproxy-controller-devops
spec:
  type: ClusterIP
  selector:
    app: ingress-default-backend
  ports:
    - name: port-backend 
      port: 80
      targetPort: 8080