apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  initContainers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 20"] 
  containers:
    - name: redis-container
      image: redis
          