apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
spec:
  containers:
  - name: nginx-liveness
    image: nginx
    livenessProbe:
      httpGet:
        path: /text.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5