apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - name: pvc-pod-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /var/log/nginx
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: =claim-log-1