apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
    - name: sidecar-container
      image: ubuntu:latest
      args:
        - sh
        - -c
        - while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done
      volumeMounts:
        - mountPath: /var/log/nginx
          name: shared-logs

    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /var/log/nginx
          name: shared-logs

  volumes:
    - name: shared-logs
      emptyDir: {}